GridLayoutExample:

<GridLayoutExample>:
    #orientation: 'vertical'
    rows: 4
    cols: 2

    Button:
        text: 'Back Button'
    Label:
        text: 'Face2Face'
        color: 'black'
    Button:
        text: 'Profile Pic1'
    Button:
        text: 'Profile Pic2'
    Button:
        text: 'Profile Pic3'
    Button:
        text: 'Profile Pic4'
    Button:
        text: 'Profile Pic5'
