GridLayoutExample:

<GridLayoutExample>:
    #orientation: 'vertical'
    rows: 4
    cols: 2

    Button:
        text: 'Back Button'
    Label:
        text: 'Face2Face'
        color: 'black'
    Button:
        text: 'Request Pic1'
    Button:
        text: 'Request Pic2'
    Button:
        text: 'Request Pic3'
    Button:
        text: 'Request Pic4'
    Button:
        text: 'Request Pic5'
