GridLayoutExample:

<GridLayoutExample>:
    #orientation: 'vertical'
    rows: 4
    cols: 2

    Button:
        text: 'Back Button'
    Label:
    Label:
        text: 'Your Matches'
        color: 'black'
    Label:

    Label:
        text: 'Leyla'
        color: 'black'
    Button:
        text: 'Leylas most matched pic'
        color: 'black'
    Label:
        text: 'Libby'
        color: 'black'
    Button:
        text: 'Libby most matched pic'
        color: 'black'